"""test running migrations

Revision ID: e70a79664fb2
Revises: 0841a2d5d3f1
Create Date: 2023-10-17 22:12:43.861355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70a79664fb2'
down_revision = '0841a2d5d3f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
